user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    sendfile on;
    keepalive_timeout 65;

    client_max_body_size 15M; # Crucial for crop image uploads

    upstream web_srv {
        server web:3000;
    }

    upstream backend_srv {
        server backend:7860;
    }

    server {
        listen 80;
        server_name localhost;

        # Webroot path for Certbot verification
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Routing backend API requests
        location /api {
            proxy_pass http://backend_srv;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Routing frontend
        location / {
            proxy_pass http://web_srv;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
